package com.jarana.entities;
// Generated Feb 21, 2017 10:30:35 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer", catalog = "ecomm")
public class Customer implements java.io.Serializable {

	private Long cuCustomerId;
	private Tax tax;
	private String cuFirstName;
	private String cuLastName;
	private String cuAddress;
	private String cuCity;
	private Integer cuZipCode;
	private String cuTelephone;
	private Set<Sale> sales = new HashSet<Sale>(0);

	public Customer() {
	}

	public Customer(Long cuCustomerId) {
		this.cuCustomerId = cuCustomerId;
	}

	public Customer(Long cuCustomerId, Tax tax, String cuFirstName, String cuLastName, String cuAddress, String cuCity,
			Integer cuZipCode, String cuTelephone, Set<Sale> sales) {
		this.cuCustomerId = cuCustomerId;
		this.tax = tax;
		this.cuFirstName = cuFirstName;
		this.cuLastName = cuLastName;
		this.cuAddress = cuAddress;
		this.cuCity = cuCity;
		this.cuZipCode = cuZipCode;
		this.cuTelephone = cuTelephone;
		this.sales = sales;
	}

	@Id

	@Column(name = "cu_customer_id", unique = true, nullable = false)
	public Long getCuCustomerId() {
		return this.cuCustomerId;
	}

	public void setCuCustomerId(Long cuCustomerId) {
		this.cuCustomerId = cuCustomerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cu_state")
	public Tax getTax() {
		return this.tax;
	}

	
	public void setTax(Tax tax) {
		this.tax = tax;
	}

	@Column(name = "cu_first_name", length = 40)
	public String getCuFirstName() {
		return this.cuFirstName;
	}

	public void setCuFirstName(String cuFirstName) {
		this.cuFirstName = cuFirstName;
	}

	@Column(name = "cu_last_name", length = 40)
	public String getCuLastName() {
		return this.cuLastName;
	}

	public void setCuLastName(String cuLastName) {
		this.cuLastName = cuLastName;
	}

	@Column(name = "cu_address")
	public String getCuAddress() {
		return this.cuAddress;
	}

	public void setCuAddress(String cuAddress) {
		this.cuAddress = cuAddress;
	}

	@Column(name = "cu_city", length = 16)
	public String getCuCity() {
		return this.cuCity;
	}

	public void setCuCity(String cuCity) {
		this.cuCity = cuCity;
	}

	@Column(name = "cu_zip_code")
	public Integer getCuZipCode() {
		return this.cuZipCode;
	}

	public void setCuZipCode(Integer cuZipCode) {
		this.cuZipCode = cuZipCode;
	}

	@Column(name = "cu_telephone", length = 16)
	public String getCuTelephone() {
		return this.cuTelephone;
	}

	public void setCuTelephone(String cuTelephone) {
		this.cuTelephone = cuTelephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Sale> getSales() {
		return this.sales;
	}

	
	public void setSales(Set<Sale> sales) {
		this.sales = sales;
	}

}
