package com.jarana.entities;
// Generated Feb 21, 2017 10:30:35 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "Tax", catalog = "ecomm")
public class Tax implements java.io.Serializable {

	private Integer taxId;
	
	@Id
	@Column(name="ta_id")
	public Integer getTaxId() {
		return taxId;
	}

	public void setTaxId(Integer taxId) {
		this.taxId = taxId;
	}


	private String taStateCode;
	private String taCategory;
	private BigDecimal taTaxPct;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Tax() {
	}

	public Tax(String taStateCode) {
		this.taStateCode = taStateCode;
	}

	public Tax(String taStateCode, String taCategory, BigDecimal taTaxPct, Set<Customer> customers) {
		this.taStateCode = taStateCode;
		this.taCategory = taCategory;
		this.taTaxPct = taTaxPct;
		this.customers = customers;
	}

	

	@Column(name = "ta_state_code", unique = true, nullable = false, length = 2)
	public String getTaStateCode() {
		return this.taStateCode;
	}

	public void setTaStateCode(String taStateCode) {
		this.taStateCode = taStateCode;
	}

	@Column(name = "ta_category", length = 12)
	public String getTaCategory() {
		return this.taCategory;
	}

	public void setTaCategory(String taCategory) {
		this.taCategory = taCategory;
	}

	@Column(name = "ta_tax_pct", precision = 5)
	public BigDecimal getTaTaxPct() {
		return this.taTaxPct;
	}

	public void setTaTaxPct(BigDecimal taTaxPct) {
		this.taTaxPct = taTaxPct;
	}

}
