package com.jarana.entities;
// Generated Feb 21, 2017 10:30:35 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Vendor generated by hbm2java
 */
@Entity
@Table(name = "Vendor", catalog = "ecomm")
public class Vendor implements java.io.Serializable {

	private Long veVendorNumber;
	private String veVendorName;
	private String veAddress;
	private String veCity;
	private String veState;
	private Integer veZipCode;
	private String veTelephone;
	private Set<Part> parts = new HashSet<Part>(0);

	public Vendor() {
	}

	public Vendor(Long veVendorNumber) {
		this.veVendorNumber = veVendorNumber;
	}

	public Vendor(Long veVendorNumber, String veVendorName, String veAddress, String veCity, String veState,
			Integer veZipCode, String veTelephone, Set<Part> parts) {
		this.veVendorNumber = veVendorNumber;
		this.veVendorName = veVendorName;
		this.veAddress = veAddress;
		this.veCity = veCity;
		this.veState = veState;
		this.veZipCode = veZipCode;
		this.veTelephone = veTelephone;
		this.parts = parts;
	}

	@Id

	@Column(name = "ve_vendor_number", unique = true, nullable = false)
	public Long getVeVendorNumber() {
		return this.veVendorNumber;
	}

	public void setVeVendorNumber(Long veVendorNumber) {
		this.veVendorNumber = veVendorNumber;
	}

	@Column(name = "ve_vendor_name", length = 60)
	public String getVeVendorName() {
		return this.veVendorName;
	}

	public void setVeVendorName(String veVendorName) {
		this.veVendorName = veVendorName;
	}

	@Column(name = "ve_address")
	public String getVeAddress() {
		return this.veAddress;
	}

	public void setVeAddress(String veAddress) {
		this.veAddress = veAddress;
	}

	@Column(name = "ve_city", length = 16)
	public String getVeCity() {
		return this.veCity;
	}

	public void setVeCity(String veCity) {
		this.veCity = veCity;
	}

	@Column(name = "ve_state", length = 2)
	public String getVeState() {
		return this.veState;
	}

	public void setVeState(String veState) {
		this.veState = veState;
	}

	@Column(name = "ve_zip_code")
	public Integer getVeZipCode() {
		return this.veZipCode;
	}

	public void setVeZipCode(Integer veZipCode) {
		this.veZipCode = veZipCode;
	}

	@Column(name = "ve_telephone", length = 16)
	public String getVeTelephone() {
		return this.veTelephone;
	}

	public void setVeTelephone(String veTelephone) {
		this.veTelephone = veTelephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Part> getParts() {
		return this.parts;
	}

	@JsonIgnore
	public void setParts(Set<Part> parts) {
		this.parts = parts;
	}

}
